# Generated by Django 4.2.1 on 2023-05-24 14:48

import classifier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fasta', models.FileField(upload_to=classifier.models.submission_handler)),
            ],
        ),
    ]
