# Generated by Django 4.2.1 on 2023-05-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='fasta',
            new_name='file',
        ),
    ]
